---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    pod-security.kubernetes.io/enforce: {{ .Values.namespace.podSecurity.enforce | default "privileged" }}
    pod-security.kubernetes.io/audit: {{ .Values.namespace.podSecurity.audit | default "privileged" }}
    pod-security.kubernetes.io/warn: {{ .Values.namespace.podSecurity.warn | default "privileged" }}
