kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Chart.Name }}-data"
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumes.data.size | quote }}
  {{- if .Values.volumes.storageClassName }}
  storageClassName: {{ .Values.volumes.storageClassName | quote }}
  {{- end }}
  {{- if .Values.volumes.annotations }}
  annotations:
    {{- toYaml .Values.volumes.annotations | nindent 4 }}
  {{- end }}
