---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}"
  namespace: steam-servers
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}"
      release: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
        release: "{{ .Release.Name }}"
    spec:
      securityContext:
        runAsUser: 10000
        runAsGroup: 10000
        fsGroup: 10000
      initContainers:
      - name: init-permissions
        image: busybox:latest
        command: ["sh", "-c"]
        args:
          - |
            find /home/steam/enshrouded/savegame -path /home/steam/enshrouded/savegame/lost+found -prune -o -exec chown -R 10000:10000 {} +;
            #chown -R 10000:10000 /home/steam/enshrouded/enshrouded_server.json;
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
        - name: data
          mountPath: /home/steam/enshrouded/savegame
        - name: enshrouded-config
          mountPath: /home/steam/enshrouded/enshrouded_server.json
          subPath: enshrouded_server.json
      containers:
      - name: "{{ .Chart.Name }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
              - SYS_PTRACE
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: SERVER_NAME
          value: {{ .Values.config.serverName | squote }}
        - name: SERVER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: enshrouded-secrets
              key: ADMIN_PASSWORD
        - name: QUERY_PORT
          value: {{ .Values.config.queryPort | squote }}
        - name: SERVER_SLOTS
          value: {{ .Values.config.serverSlots | squote }}
        ports:
        - name: query-port
          containerPort: {{ .Values.config.queryPort | int }}
          protocol: UDP
        volumeMounts:
        - name: data
          mountPath: /home/steam/enshrouded/savegame
        - name: enshrouded-config
          mountPath: /home/steam/enshrouded/enshrouded_server.json
          subPath: enshrouded_server.json
        - name: config-volume
          mountPath: /tmp
        securityContext:
          allowPrivilegeEscalation: false
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: "{{ .Chart.Name }}-data"
      - name: enshrouded-config
        configMap:
          name: enshrouded-config
      - name: config-volume
        emptyDir: {}
