---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: enshrouded
  namespace: {{ .Values.namespace }}
  labels:
    app: enshrouded
spec:
  replicas: {{ .Values.statefulset.replicas }}
  selector:
    matchLabels:
      app: enshrouded
  serviceName: "enshrouded"
  template:
    metadata:
      labels:
        app: enshrouded
    spec:
      securityContext:
        runAsUser: {{ .Values.statefulset.securityContext.runAsUser }}
        runAsGroup: {{ .Values.statefulset.securityContext.runAsGroup }}
        fsGroup: {{ .Values.statefulset.securityContext.fsGroup }}
      containers:
        - name: enshrouded
          image: "{{ .Values.statefulset.image.repository }}:{{ .Values.statefulset.image.tag }}"
          imagePullPolicy: {{ .Values.statefulset.image.pullPolicy }}
          ports:
            - containerPort: 15637
              name: "query-port-udp"
              protocol: UDP
          volumeMounts:
            - name: enshrouded-data
              mountPath: /home/steam/enshrouded/savegame
            - name: config-volume
              mountPath: /home/steam/enshrouded/enshrouded_server.json
              subPath: enshrouded_server.json
          resources:
            requests:
              cpu: {{ .Values.statefulset.resources.requests.cpu }}
              memory: {{ .Values.statefulset.resources.requests.memory }}
            limits:
              cpu: {{ .Values.statefulset.resources.limits.cpu }}
              memory: {{ .Values.statefulset.resources.limits.memory }}
      volumes:
        - name: config-volume
          configMap:
            name: enshrouded-config
        - name: enshrouded-data
          persistentVolumeClaim:
            claimName: enshrouded-data
  volumeClaimTemplates:
  - metadata:
      name: enshrouded-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.statefulset.volumes.data.size }}
