# values.yaml
namespace:
  name: enshrouded
  podSecurity:
    enforce: privileged
    audit: privileged
    warn: privileged

config:
  server:
    name: "Enshrouded Server"
    saveDirectory: "./savegame"
    logDirectory: "./logs"
    ip: "0.0.0.0"
    queryPort: 15637
    slotCount: 16
    # Add other default configurations here

statefulset:
  replicas: 1
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: 4
      memory: 6Gi
