# Namespace name will be propagated to rest of the files
namespace:
  name: steam-servers
  podSecurity:
    enforce: privileged
    audit: privileged
    warn: privileged

#config:
#  server:
#    name: "Enshrouded Server"
#    saveDirectory: "./savegame"
#    logDirectory: "./logs"
#    ip: "0.0.0.0"
#    queryPort: 15637
#    slotCount: 16
#    # Add other default configurations here

service:
  type: cilium # Choose between 'cilium' or 'nginx'
  ports:
    - name: "query-port"
      port: 15637
      targetPort: 15637
      protocol: UDP
    - name: "game-port"
      port: 15636
      targetPort: 15636
      protocol: UDP

cilium:
  type: LoadBalancer
  annotations:
    io.cilium/lb-ipam-ips: "10.26.14.82"
    ingress.cilium.io/loadbalancer-mode: "dedicated"

nginx:
  type: ClusterIP
  annotations: {} # No HTTP-specific annotations since this is UDP traffic


# StatefulSet Configuration
statefulset:
  replicas: 1
  image:
    repository: jogaltanon/enshrouded-server
    tag: proton-latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: 4
      memory: 6Gi
  securityContext:
    runAsUser: 10000
    runAsGroup: 10000
    fsGroup: 10000
  volumes:
    data:
      # Change Storage class based on your system
      storageClassName: default
      size: 5Gi
secrets:
  adminSecret: enshrouded-secrets
  friendSecret: enshrouded-secrets
  guestSecret: enshrouded-secrets