# Namespace name will be propagated to rest of the files
namespace:
  name: enshrouded
  podSecurity:
    enforce: privileged
    audit: privileged
    warn: privileged

config:
  server:
    name: "Enshrouded Server"
    saveDirectory: "./savegame"
    logDirectory: "./logs"
    ip: "0.0.0.0"
    queryPort: 15637
    slotCount: 16
    # Add other default configurations here

# StatefulSet Configuration
statefulset:
  replicas: 1
  image:
    repository: jogaltanon/enshrouded-server
    tag: proton-latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: 4
      memory: 6Gi
  securityContext:
    runAsUser: 10000
    runAsGroup: 10000
    fsGroup: 10000
  volumes:
    data:
      # Change Storage class based on your system
      storageClassName: default
      size: 5Gi

