name: Nightly Docker Build and Updates

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Run at midnight
  schedule:
    - cron: "0 0 * * *"

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      #check out repo
      - name: Checkout code
        uses: actions/checkout@v3

      #Log into Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          DATE_TAG=$(date +%Y%m%d)
          docker build . --file .Dockerfile -t jogaltanon/enshrouded-server:nightly -t jogaltanon/enshrouded-server:$DATE_TAG .

      # Push the Docker image
      - name: Push Docker image
        run: |
          docker push jogaltanon/enshrouded-server:nightly
          docker push jogaltanon/enshrouded-server:$DATE_TAG

