name: Nightly Docker Proton Build

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Check out repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Log into Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Add Date Tags
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      # Build the Docker image
      - name: Build Docker images with 3 separate tags
        run: |
          docker build --file container/proton/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/enshrouded-server:proton-nightly -t ${{ secrets.DOCKER_USERNAME }}/enshrouded-server:proton-${{ steps.date.outputs.date }} -t ${{ secrets.DOCKER_USERNAME }}/enshrouded-server:proton-latest .

      # Wait for server save event
      - name: Wait for "[server] Saved" event in logs
        run: |
          echo "Waiting for '[server] Saved' in logs..."
          timeout 300 bash -c "until docker logs enshrouded-server 2>&1 | grep -q '\[server\] Saved'; do sleep 5; done"
          echo "'[server] Saved' detected."

      # Stop Docker container
      - name: Stop Docker container
        run: |
          echo "Stopping container..."
          docker stop enshrouded-server

      # Remove the container
      - name: Remove Docker container
        run: docker rm enshrouded-server

      # Push the Docker image nightly
      - name: Push Docker nightly image 
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/enshrouded-server:proton-nightly

      # Push same image with date tag
      - name: Push Docker image date tag
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/enshrouded-server:proton-${{ steps.date.outputs.date }}

      # Push same image with latest tag
      - name: Push Docker image with latest tag
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/enshrouded-server:proton-latest
